server:
  port: 8002

spring:
  application:
    name: provider                      # 服务与服务间的调用
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 数据库源类型
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      minmin-idle: 5        # 数据库连接最小维持数
      initial-size: 5       # 初始化连接数
      max-total: 5          # 最大连接数
      max-wait-millis: 150  # 等待连接最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件路径
  type-aliases-package: com.ttk.entities                # 实体别名类所在包
  mapper-locations: classpath:mapper/*.xml   # mapper映射文件路径

eureka:
  client:
    registerWithEureka: true          # 服务注册开关
    fetchRegistry: true               # 服务发现开关
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 单机配置:http://localhost:7001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} #当前状态中显示主机名, 配置只显示服务名和端口
    prefer-ip-address: true # 当前状态中访问路径显示成IP地址 preferIpAddress