server:
  port: 8006

spring:
  application:
    name: provider-consul          # 服务与服务间的调用
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}